#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
<<<<<<< HEAD
# Generated by Vivado on Sat May 18 11:17:03 EDT 2024
=======
# Generated by Vivado on Sat May 18 12:46:34 EDT 2024
>>>>>>> 77c5084fcb76b911115f01f83df3f386758c90aa
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -L axi_vip_v1_1_12 -L smartconnect_v1_0 -L xilinx_vip -prj fsic_tb2_vlog.prj"
xvlog --incr --relax -L uvm -L axi_vip_v1_1_12 -L smartconnect_v1_0 -L xilinx_vip -prj fsic_tb2_vlog.prj 2>&1 | tee compile.log

# compile VHDL design sources
echo "xvhdl --incr --relax -prj fsic_tb2_vhdl.prj"
xvhdl --incr --relax -prj fsic_tb2_vhdl.prj 2>&1 | tee -a compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
