#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
<<<<<<< HEAD
# Generated by Vivado on Sat May 18 11:18:17 EDT 2024
=======
# Generated by Vivado on Sat May 18 12:47:17 EDT 2024
>>>>>>> 77c5084fcb76b911115f01f83df3f386758c90aa
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
<<<<<<< HEAD
echo "xsim fsic_tb2_behav -key {Behavioral:sim_1:Functional:fsic_tb2} -tclbatch fsic_tb2.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/bd_a878.protoinst" -protoinst "protoinst_files/bd_a888.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view /home/ubuntu/Advanced_SoC/lab_4/ASoC_lab4_FSIC_FPGA/vivado/fsic_tb_behav.wcfg -log simulate.log"
xsim fsic_tb2_behav -key {Behavioral:sim_1:Functional:fsic_tb2} -tclbatch fsic_tb2.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/bd_a878.protoinst" -protoinst "protoinst_files/bd_a888.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view /home/ubuntu/Advanced_SoC/lab_4/ASoC_lab4_FSIC_FPGA/vivado/fsic_tb_behav.wcfg -log simulate.log
=======
echo "xsim fsic_tb2_behav -key {Behavioral:sim_1:Functional:fsic_tb2} -tclbatch fsic_tb2.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/bd_a878.protoinst" -protoinst "protoinst_files/bd_a888.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view /home/ubuntu/SoC_Design/homework/ASoC_lab4_FSIC_FPGA/vivado/fsic_tb_behav.wcfg -log simulate.log"
xsim fsic_tb2_behav -key {Behavioral:sim_1:Functional:fsic_tb2} -tclbatch fsic_tb2.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/bd_a878.protoinst" -protoinst "protoinst_files/bd_a888.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view /home/ubuntu/SoC_Design/homework/ASoC_lab4_FSIC_FPGA/vivado/fsic_tb_behav.wcfg -log simulate.log
>>>>>>> 77c5084fcb76b911115f01f83df3f386758c90aa

